### ISSUE TITLE
Icon size in Firefox browser

### ISSUE THREAD

**Issue by AntoninMarchardDev** [tillersystems/Stardust#385]
There is a display error on Mozilla Firefox with some icons : 

<img width="674" alt="capture d ecran 2019-02-04 a 4 54 19 pm" src="https://user-images.githubusercontent.com/29677243/52219852-c44f0400-289d-11e9-9419-9167abf94025.png">

<img width="1149" alt="capture d ecran 2019-02-04 a 4 54 29 pm" src="https://user-images.githubusercontent.com/29677243/52219864-c9ac4e80-289d-11e9-8f47-627b3dbe1501.png">

**Comment by sun-tea** [comment]
sgv size do not handle rem units on Firefox. So to fix that we need to specify size in px when we use the Icon component. Maybe we could force the use of px for Icon?
